spring:
  profiles:
    active: test
server:
  port: 8104
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://192.168.1.170:3306/mongcent_news
    username: dbuser
    password: asdQWE!@#
    initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://192.168.99.100:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://192.168.99.100:8787
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  application:
    name: search-service
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:mysql://192.168.1.170:3306/7jpz
    username: root
    password: mysql
    initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
